runtime: custom
env: flex

service: backend

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10

env_variables:
  RUST_LOG: info
  PORT: 8080
  DATABASE_URL: postgresql://postgres:password@localhost/blabout
  KINDE_DOMAIN: https://aftuh.kinde.com
  KINDE_CLIENT_ID: 86cc8835a73840638345742c900e3265
  KINDE_CLIENT_SECRET: not_applicable_for_public_client
  KINDE_REDIRECT_URI: https://blabout.com/auth/callback
  OPENROUTER_API_KEY: your_openrouter_api_key
  GOOGLE_CLOUD_PROJECT_ID: your_gcp_project_id

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
