steps:
  # Build the Rust backend
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/blabout-backend:$COMMIT_SHA',
      '-f', 'Dockerfile',
      '.'
    ]
    dir: 'backend'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/blabout-backend:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'blabout-backend',
      '--image', 'gcr.io/$PROJECT_ID/blabout-backend:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '3001',
      '--set-env-vars', 'RUST_LOG=info,PORT=3001',
      '--memory', '1Gi',
      '--cpu', '1',
      '--max-instances', '10',
      '--timeout', '300'
    ]

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/blabout-backend:$COMMIT_SHA'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  substitutionOption: 'ALLOW_LOOSE'
